"""SSPL Packer — pack multiple MIDI files into a single SSPL container.

Usage:
    python SSPL_Packer.py song1.mid song2.mid ... -o playlist.sspl
    python SSPL_Packer.py *.mid -o playlist.sspl -c playlist_data.c
    python SSPL_Packer.py *.mid -o playlist.sspl -c playlist_data.c --template 8051_sdcc
"""

from __future__ import absolute_import
import struct
import os
import argparse
import time
from io import StringIO

from MidiToSimpleScore import (
    readMidiFile, readMidiFileFull, analyzeNoteList,
    calcTranspose, calcEncodingTranspose,
    generateEventSetList, generateDeltaBinV3, addHeader,
    formatFileByParam,
)

SSPL_MAGIC = b'SSPL'
SSPL_VERSION = 0x01
SSPL_HEADER_SIZE = 12
SSPL_ENTRY_SIZE = 8


def build_sspl(midi_files, voiceCenterNote=60, lowerBoundNote=0,
               upperBoundNote=127, tickPerSecond=125,
               includeNoteOnVelocity=False, includeNoteOffVelocity=False):
    """Convert MIDI files to SSCR, pack into SSPL binary.
    Returns (sspl_bytes, entry_info_list).
    """

    sscr_blocks = []
    entry_info = []

    for path in midi_files:
        noteOnList = readMidiFile(path)
        centroid, lowest, highest = analyzeNoteList(noteOnList)

        voiceTranspose = calcTranspose(centroid, lowest, highest,
                                       voiceCenterNote, lowerBoundNote, upperBoundNote)
        encodingTranspose, totalTranspose = calcEncodingTranspose(
            centroid, lowest, highest, voiceTranspose, lowerBoundNote, upperBoundNote)

        eventList = readMidiFileFull(path)
        eventSetList = generateEventSetList(eventList)
        raw = generateDeltaBinV3(eventSetList, tickPerSecond, totalTranspose,
                                 includeNoteOnVelocity, includeNoteOffVelocity)
        sscr_data = addHeader(raw, tickPerSecond, totalTranspose,
                              includeNoteOnVelocity, includeNoteOffVelocity)

        sscr_blocks.append(sscr_data)
        entry_info.append({
            'name': os.path.basename(path),
            'size': len(sscr_data),
            'centroid': centroid,
            'lowest': lowest,
            'highest': highest,
            'voiceTranspose': voiceTranspose,
            'encodingTranspose': encodingTranspose,
            'totalTranspose': totalTranspose,
        })

    data_start = SSPL_HEADER_SIZE + len(sscr_blocks) * SSPL_ENTRY_SIZE

    header = bytearray()
    header.extend(SSPL_MAGIC)
    header.append(SSPL_VERSION)
    header.append(0x00)  # Flags
    header += struct.pack('<H', len(sscr_blocks))
    header += struct.pack('<I', 0)  # Reserved

    table = bytearray()
    offset = data_start
    for blk in sscr_blocks:
        table += struct.pack('<II', offset, len(blk))
        offset += len(blk)

    sspl = header + table
    for blk in sscr_blocks:
        sspl += blk

    return sspl, entry_info


def generate_c_array(sspl_bytes, entry_info):
    """Generate a C const array with rich metadata comment block."""

    total = len(sspl_bytes)
    col_width = 16
    header_bytes = SSPL_HEADER_SIZE + len(entry_info) * SSPL_ENTRY_SIZE

    out = StringIO()

    out.write("/*\n")
    out.write(" * SSPL Playlist — generated by SSPL_Packer.py\n")
    out.write(" * Date: %s\n" % time.strftime('%Y-%m-%d %H:%M:%S'))
    out.write(" *\n")
    out.write(" * Container:  %d score(s),  %d bytes total\n" %
              (len(entry_info), total))
    out.write(" *   Header:       %d B (magic + version + flags + count + reserved)\n" %
              SSPL_HEADER_SIZE)
    out.write(" *   Entry table:  %d B (%d entries × %d B)\n" %
              (len(entry_info) * SSPL_ENTRY_SIZE, len(entry_info), SSPL_ENTRY_SIZE))
    out.write(" *   Score data:   %d B\n" % (total - header_bytes))
    out.write(" *\n")

    name_w = max(len(e['name']) for e in entry_info) if entry_info else 20

    # Per-score detail header
    for i, e in enumerate(entry_info):
        out.write(" * ── Score %d ──\n" % i)
        out.write(" *   Name:              %s\n" % e['name'])
        out.write(" *   SSCR size:         %d B\n" % e['size'])
        out.write(" *   Original range:    %d – %d  (centroid: %d)\n" %
                  (e['lowest'], e['highest'], e['centroid']))
        out.write(" *   Voice transpose:   %+d  -> centroid at %d\n" %
                  (e['voiceTranspose'], e['centroid'] + e['voiceTranspose']))
        out.write(" *   Encoding transpose:%+d  -> centroid at %d\n" %
                  (e['encodingTranspose'], e['centroid'] + e['totalTranspose']))
        out.write(" *   Total transpose:   %+d  (stored in SSCR header)\n" %
                  e['totalTranspose'])
        out.write(" *   Encoded range:     %d – %d  (0–61 = direct, 62–127 = extended)\n" %
                  (e['lowest'] + e['totalTranspose'], e['highest'] + e['totalTranspose']))
        out.write(" *\n")

    out.write(" * Playback:\n")
    out.write(" *   #include \"sscr_player.c\"\n")
    out.write(" *   #include \"sspl_player.h\"\n")
    out.write(" *\n")
    out.write(" *   SSPL_File sspl;\n")
    out.write(" *   SSPL_Init(&sspl, Playlist, sizeof(Playlist));\n")
    out.write(" *\n")
    out.write(" *   for (uint16_t i = 0; i < SSPL_GetCount(&sspl); i++) {\n")
    out.write(" *       const uint8_t *d; uint32_t s;\n")
    out.write(" *       SSPL_GetEntry(&sspl, i, &d, &s);\n")
    out.write(" *       SSCR_Player p;\n")
    out.write(" *       SSCR_Init(&p, d, s);\n")
    out.write(" *       // play until finished ...\n")
    out.write(" *   }\n")
    out.write(" *\n")
    out.write(" * Note: SSCR_Init() reads TotalTranspose from the SSCR header\n")
    out.write(" *       and auto-restores original pitch before synth callbacks.\n")
    out.write(" */\n\n")

    out.write("const unsigned char Playlist[%d] = {\n" % total)

    col = 0
    for i, byte in enumerate(sspl_bytes):
        if col == 0:
            out.write("    ")
        out.write("0x%02x" % byte)
        if i < total - 1:
            out.write(", ")
        col += 1
        if col >= col_width:
            out.write("\n")
            col = 0

    if col > 0:
        out.write("\n")
    out.write("};\n")

    return out.getvalue()


def generate_c_with_template(sspl_bytes, entry_info, template_name, output_file):
    """Generate C code using a built-in or external template file."""

    from MidiToSimpleScore import getCStyleSampleDataString

    scriptDir = os.path.dirname(os.path.abspath(__file__))

    if os.path.isfile(template_name):
        templatePath = template_name
    else:
        templateDir = os.path.join(scriptDir, 'template', template_name)
        candidates = [os.path.join(templateDir, f)
                      for f in os.listdir(templateDir)
                      if f.endswith('.template')]
        if not candidates:
            raise FileNotFoundError(
                f"No template found for '{template_name}' in {templateDir}")
        templatePath = candidates[0]

    meta_lines = [
        "SSPL Playlist — %d score(s), %d bytes total" % (len(entry_info), len(sspl_bytes)),
        "Date: %s" % time.strftime('%Y-%m-%d %H:%M:%S'),
        "TickPerSecond: 125",
        "",
        "Transpose layers (auto-restored by player):",
        "  Voice transpose:     instrument centering (-> voiceCenterNote)",
        "  Encoding transpose:  compression optimization (-> centroid ~30)",
        "  Total transpose:     voice + encoding (stored in SSCR header)",
        "  The C player applies inverse automatically via SSCR_Init().",
        "",
    ]
    for i, e in enumerate(entry_info):
        meta_lines.append("── Score %d: %s" % (i, e['name']))
        meta_lines.append("    Original:   centroid=%d  range=%d-%d" %
                          (e['centroid'], e['lowest'], e['highest']))
        meta_lines.append("    Voice T:    %+d  -> centroid=%d" %
                          (e['voiceTranspose'], e['centroid'] + e['voiceTranspose']))
        meta_lines.append("    Encoding T: %+d  -> centroid=%d (encoded)" %
                          (e['encodingTranspose'], e['centroid'] + e['totalTranspose']))
        meta_lines.append("    Total T:    %+d  (in header, auto-restored by player)" %
                          e['totalTranspose'])
        meta_lines.append("    Encoded:     range=%d-%d  size=%d B" %
                          (e['lowest'] + e['totalTranspose'],
                           e['highest'] + e['totalTranspose'],
                           e['size']))

    scoreMetaInfo = '\n'.join(meta_lines)
    scoreBytesDataString = getCStyleSampleDataString(sspl_bytes, 16, dataDescription='')

    paramDict = {
        'ScoreDataLen': len(sspl_bytes),
        'ScoreMetaInfo': scoreMetaInfo,
        'ScoreData': scoreBytesDataString,
    }

    formatFileByParam(templatePath, output_file, paramDict)


def main():
    parser = argparse.ArgumentParser(
        description='Pack multiple MIDI files into SSPL container.')

    parser.add_argument('midi_files', nargs='+', help='MIDI files to pack')
    parser.add_argument('-o', '--output', default='playlist.sspl',
                        help='Output SSPL binary file path')
    parser.add_argument('-c', '--c-output', default=None,
                        help='Output C array file path')
    parser.add_argument('--template', type=str, default=None,
                        help='Template file for C code generation (requires -c)')
    parser.add_argument('--voiceCenterNote', type=int, default=60,
                        help='Center note of target voice (default C4=60)')
    parser.add_argument('--tickPerSecond', type=int, default=125)
    parser.add_argument('--includeNoteOnVelocity', action='store_true')
    parser.add_argument('--includeNoteOffVelocity', action='store_true')
    args = parser.parse_args()

    sspl_data, info = build_sspl(
        args.midi_files,
        voiceCenterNote=args.voiceCenterNote,
        tickPerSecond=args.tickPerSecond,
        includeNoteOnVelocity=args.includeNoteOnVelocity,
        includeNoteOffVelocity=args.includeNoteOffVelocity,
    )

    # Binary output
    with open(args.output, 'wb') as f:
        f.write(sspl_data)

    total = sum(e['size'] for e in info)
    header_table = SSPL_HEADER_SIZE + len(info) * SSPL_ENTRY_SIZE
    print(f"SSPL written: {args.output}")
    print(f"  Scores: {len(info)}")
    print(f"  Header + Table: {header_table} B")
    print(f"  SSCR data: {total} B")
    print(f"  Total: {len(sspl_data)} B")
    print()
    for i, e in enumerate(info):
        print(f"  [{i}] {e['name']:40s} {e['size']:>6d} B  "
              f"centroid={e['centroid']:>3d}  range={e['lowest']:>3d}-{e['highest']:<4d}  "
              f"totalTranspose={e['totalTranspose']:>4d}")

    # C array output
    if args.c_output:
        if args.template:
            generate_c_with_template(sspl_data, info, args.template, args.c_output)
            print(f"\nC source (template) written: {args.c_output}")
        else:
            c_code = generate_c_array(sspl_data, info)
            with open(args.c_output, 'w', encoding='utf-8') as f:
                f.write(c_code)
            print(f"\nC source written: {args.c_output}")


if __name__ == "__main__":
    main()
